### ISSUE TITLE
RuntimeError: The size of tensor a (77) must match the size of tensor b (231) at non-singleton dimension 1

### ISSUE THREAD

**Issue by YKefasu** [muerrilla/stable-diffusion-NPW#1]
Error executing callback cfg_denoiser_callback for C:\Stable Diffusion WebUI\extensions\stable-diffusion-NPW\scripts\npw.py
Traceback (most recent call last):
  File "C:\Stable Diffusion WebUI\modules\script_callbacks.py", line 167, in cfg_denoiser_callback
    c.callback(params)
  File "C:\Stable Diffusion WebUI\extensions\stable-diffusion-NPW\scripts\npw.py", line 62, in denoiser_callback
    new_uncond = torch.lerp(self.empty_uncond, uncond, self.weight)
RuntimeError: The size of tensor a (77) must match the size of tensor b (231) at non-singleton dimension 1

**Comment by muerrilla** [comment]
This was fixed in this [commit](https://github.com/muerrilla/stable-diffusion-NPW/commit/f329babebdd156bfad1ca6588f842a2d8d3586f8).  Please update and report back if possible.
